import { createRouter as createTanStackRouter } from '@tanstack/react-router';

import { routeTree } from './routeTree.gen';

// TanStack Start picks up this `getRouter` export (src/router.tsx) to build the app router on both
// the server (SSR) and the client (hydration). `routeTree.gen.ts` is generated by the TanStack Start
// Vite plugin on `vite dev` / `vite build`.
export function getRouter() {
  return createTanStackRouter({
    routeTree,
    scrollRestoration: true,
    defaultPreload: 'intent',
  });
}

declare module '@tanstack/react-router' {
  interface Register {
    router: ReturnType<typeof getRouter>;
  }
}
