/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrayRouteRouteImport } from './routes/tray/route'
import { Route as SignupRouteRouteImport } from './routes/signup/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ScheduleRouteRouteImport } from './routes/schedule/route'
import { Route as OnboardingRouteRouteImport } from './routes/onboarding/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as InboxRouteRouteImport } from './routes/inbox/route'
import { Route as BacklogRouteRouteImport } from './routes/backlog/route'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as WorkspacesNewRouteRouteImport } from './routes/workspaces/new/route'
import { Route as SpecsSpecIdRouteRouteImport } from './routes/specs/$specId/route'
import { Route as SettingsSectionIdRouteRouteImport } from './routes/settings/$sectionId/route'
import { Route as BacklogSpecsRouteRouteImport } from './routes/backlog/specs/route'
import { Route as BacklogActionsRouteRouteImport } from './routes/backlog/actions/route'
import { Route as SettingsIndexRouteRouteImport } from './routes/settings/index/route'
import { Route as ScheduleBlockBlockIdRouteRouteImport } from './routes/schedule/block/$blockId/route'

const TrayRouteRoute = TrayRouteRouteImport.update({
  id: '/tray',
  path: '/tray',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRouteRoute = SignupRouteRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRouteRoute = ScheduleRouteRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRouteRoute = OnboardingRouteRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRouteRoute = InboxRouteRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRouteRoute = BacklogRouteRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesNewRouteRoute = WorkspacesNewRouteRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsSpecIdRouteRoute = SpecsSpecIdRouteRouteImport.update({
  id: '/specs/$specId',
  path: '/specs/$specId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionIdRouteRoute = SettingsSectionIdRouteRouteImport.update({
  id: '/$sectionId',
  path: '/$sectionId',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const BacklogSpecsRouteRoute = BacklogSpecsRouteRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => BacklogRouteRoute,
} as any)
const BacklogActionsRouteRoute = BacklogActionsRouteRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => BacklogRouteRoute,
} as any)
const SettingsIndexRouteRoute = SettingsIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ScheduleBlockBlockIdRouteRoute =
  ScheduleBlockBlockIdRouteRouteImport.update({
    id: '/block/$blockId',
    path: '/block/$blockId',
    getParentRoute: () => ScheduleRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/backlog': typeof BacklogRouteRouteWithChildren
  '/inbox': typeof InboxRouteRoute
  '/login': typeof LoginRouteRoute
  '/onboarding': typeof OnboardingRouteRoute
  '/schedule': typeof ScheduleRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/signup': typeof SignupRouteRoute
  '/tray': typeof TrayRouteRoute
  '/settings/': typeof SettingsIndexRouteRoute
  '/backlog/actions': typeof BacklogActionsRouteRoute
  '/backlog/specs': typeof BacklogSpecsRouteRoute
  '/settings/$sectionId': typeof SettingsSectionIdRouteRoute
  '/specs/$specId': typeof SpecsSpecIdRouteRoute
  '/workspaces/new': typeof WorkspacesNewRouteRoute
  '/schedule/block/$blockId': typeof ScheduleBlockBlockIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/backlog': typeof BacklogRouteRouteWithChildren
  '/inbox': typeof InboxRouteRoute
  '/login': typeof LoginRouteRoute
  '/onboarding': typeof OnboardingRouteRoute
  '/schedule': typeof ScheduleRouteRouteWithChildren
  '/settings': typeof SettingsIndexRouteRoute
  '/signup': typeof SignupRouteRoute
  '/tray': typeof TrayRouteRoute
  '/backlog/actions': typeof BacklogActionsRouteRoute
  '/backlog/specs': typeof BacklogSpecsRouteRoute
  '/settings/$sectionId': typeof SettingsSectionIdRouteRoute
  '/specs/$specId': typeof SpecsSpecIdRouteRoute
  '/workspaces/new': typeof WorkspacesNewRouteRoute
  '/schedule/block/$blockId': typeof ScheduleBlockBlockIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/backlog': typeof BacklogRouteRouteWithChildren
  '/inbox': typeof InboxRouteRoute
  '/login': typeof LoginRouteRoute
  '/onboarding': typeof OnboardingRouteRoute
  '/schedule': typeof ScheduleRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/signup': typeof SignupRouteRoute
  '/tray': typeof TrayRouteRoute
  '/settings/': typeof SettingsIndexRouteRoute
  '/backlog/actions': typeof BacklogActionsRouteRoute
  '/backlog/specs': typeof BacklogSpecsRouteRoute
  '/settings/$sectionId': typeof SettingsSectionIdRouteRoute
  '/specs/$specId': typeof SpecsSpecIdRouteRoute
  '/workspaces/new': typeof WorkspacesNewRouteRoute
  '/schedule/block/$blockId': typeof ScheduleBlockBlockIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backlog'
    | '/inbox'
    | '/login'
    | '/onboarding'
    | '/schedule'
    | '/settings'
    | '/signup'
    | '/tray'
    | '/settings/'
    | '/backlog/actions'
    | '/backlog/specs'
    | '/settings/$sectionId'
    | '/specs/$specId'
    | '/workspaces/new'
    | '/schedule/block/$blockId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backlog'
    | '/inbox'
    | '/login'
    | '/onboarding'
    | '/schedule'
    | '/settings'
    | '/signup'
    | '/tray'
    | '/backlog/actions'
    | '/backlog/specs'
    | '/settings/$sectionId'
    | '/specs/$specId'
    | '/workspaces/new'
    | '/schedule/block/$blockId'
  id:
    | '__root__'
    | '/'
    | '/backlog'
    | '/inbox'
    | '/login'
    | '/onboarding'
    | '/schedule'
    | '/settings'
    | '/signup'
    | '/tray'
    | '/settings/'
    | '/backlog/actions'
    | '/backlog/specs'
    | '/settings/$sectionId'
    | '/specs/$specId'
    | '/workspaces/new'
    | '/schedule/block/$blockId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  BacklogRouteRoute: typeof BacklogRouteRouteWithChildren
  InboxRouteRoute: typeof InboxRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  OnboardingRouteRoute: typeof OnboardingRouteRoute
  ScheduleRouteRoute: typeof ScheduleRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  SignupRouteRoute: typeof SignupRouteRoute
  TrayRouteRoute: typeof TrayRouteRoute
  SpecsSpecIdRouteRoute: typeof SpecsSpecIdRouteRoute
  WorkspacesNewRouteRoute: typeof WorkspacesNewRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tray': {
      id: '/tray'
      path: '/tray'
      fullPath: '/tray'
      preLoaderRoute: typeof TrayRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs/$specId': {
      id: '/specs/$specId'
      path: '/specs/$specId'
      fullPath: '/specs/$specId'
      preLoaderRoute: typeof SpecsSpecIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$sectionId': {
      id: '/settings/$sectionId'
      path: '/$sectionId'
      fullPath: '/settings/$sectionId'
      preLoaderRoute: typeof SettingsSectionIdRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/backlog/specs': {
      id: '/backlog/specs'
      path: '/specs'
      fullPath: '/backlog/specs'
      preLoaderRoute: typeof BacklogSpecsRouteRouteImport
      parentRoute: typeof BacklogRouteRoute
    }
    '/backlog/actions': {
      id: '/backlog/actions'
      path: '/actions'
      fullPath: '/backlog/actions'
      preLoaderRoute: typeof BacklogActionsRouteRouteImport
      parentRoute: typeof BacklogRouteRoute
    }
    '/settings/': {
      id: '/settings/'
      path: ''
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/schedule/block/$blockId': {
      id: '/schedule/block/$blockId'
      path: '/block/$blockId'
      fullPath: '/schedule/block/$blockId'
      preLoaderRoute: typeof ScheduleBlockBlockIdRouteRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
  }
}

interface BacklogRouteRouteChildren {
  BacklogActionsRouteRoute: typeof BacklogActionsRouteRoute
  BacklogSpecsRouteRoute: typeof BacklogSpecsRouteRoute
}

const BacklogRouteRouteChildren: BacklogRouteRouteChildren = {
  BacklogActionsRouteRoute: BacklogActionsRouteRoute,
  BacklogSpecsRouteRoute: BacklogSpecsRouteRoute,
}

const BacklogRouteRouteWithChildren = BacklogRouteRoute._addFileChildren(
  BacklogRouteRouteChildren,
)

interface ScheduleRouteRouteChildren {
  ScheduleBlockBlockIdRouteRoute: typeof ScheduleBlockBlockIdRouteRoute
}

const ScheduleRouteRouteChildren: ScheduleRouteRouteChildren = {
  ScheduleBlockBlockIdRouteRoute: ScheduleBlockBlockIdRouteRoute,
}

const ScheduleRouteRouteWithChildren = ScheduleRouteRoute._addFileChildren(
  ScheduleRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsIndexRouteRoute: typeof SettingsIndexRouteRoute
  SettingsSectionIdRouteRoute: typeof SettingsSectionIdRouteRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRouteRoute: SettingsIndexRouteRoute,
  SettingsSectionIdRouteRoute: SettingsSectionIdRouteRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  BacklogRouteRoute: BacklogRouteRouteWithChildren,
  InboxRouteRoute: InboxRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  OnboardingRouteRoute: OnboardingRouteRoute,
  ScheduleRouteRoute: ScheduleRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  SignupRouteRoute: SignupRouteRoute,
  TrayRouteRoute: TrayRouteRoute,
  SpecsSpecIdRouteRoute: SpecsSpecIdRouteRoute,
  WorkspacesNewRouteRoute: WorkspacesNewRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
