/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthTrayRouteImport } from './routes/_auth/tray'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthScheduleRouteImport } from './routes/_auth/schedule'
import { Route as AuthInsightsRouteImport } from './routes/_auth/insights'
import { Route as AuthBacklogRouteImport } from './routes/_auth/backlog'
import { Route as AuthSpecsSpecIdRouteImport } from './routes/_auth/specs.$specId'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTrayRoute = AuthTrayRouteImport.update({
  id: '/tray',
  path: '/tray',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)
const AuthScheduleRoute = AuthScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInsightsRoute = AuthInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBacklogRoute = AuthBacklogRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSpecsSpecIdRoute = AuthSpecsSpecIdRouteImport.update({
  id: '/specs/$specId',
  path: '/specs/$specId',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/backlog': typeof AuthBacklogRoute
  '/insights': typeof AuthInsightsRoute
  '/schedule': typeof AuthScheduleRoute
  '/settings': typeof AuthSettingsRoute
  '/tray': typeof AuthTrayRoute
  '/specs/$specId': typeof AuthSpecsSpecIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/backlog': typeof AuthBacklogRoute
  '/insights': typeof AuthInsightsRoute
  '/schedule': typeof AuthScheduleRoute
  '/settings': typeof AuthSettingsRoute
  '/tray': typeof AuthTrayRoute
  '/': typeof AuthIndexRoute
  '/specs/$specId': typeof AuthSpecsSpecIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/_auth/backlog': typeof AuthBacklogRoute
  '/_auth/insights': typeof AuthInsightsRoute
  '/_auth/schedule': typeof AuthScheduleRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/tray': typeof AuthTrayRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/specs/$specId': typeof AuthSpecsSpecIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/backlog'
    | '/insights'
    | '/schedule'
    | '/settings'
    | '/tray'
    | '/specs/$specId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/onboarding'
    | '/backlog'
    | '/insights'
    | '/schedule'
    | '/settings'
    | '/tray'
    | '/'
    | '/specs/$specId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/onboarding'
    | '/_auth/backlog'
    | '/_auth/insights'
    | '/_auth/schedule'
    | '/_auth/settings'
    | '/_auth/tray'
    | '/_auth/'
    | '/_auth/specs/$specId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tray': {
      id: '/_auth/tray'
      path: '/tray'
      fullPath: '/tray'
      preLoaderRoute: typeof AuthTrayRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/schedule': {
      id: '/_auth/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthScheduleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/insights': {
      id: '/_auth/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AuthInsightsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/backlog': {
      id: '/_auth/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof AuthBacklogRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/specs/$specId': {
      id: '/_auth/specs/$specId'
      path: '/specs/$specId'
      fullPath: '/specs/$specId'
      preLoaderRoute: typeof AuthSpecsSpecIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthBacklogRoute: typeof AuthBacklogRoute
  AuthInsightsRoute: typeof AuthInsightsRoute
  AuthScheduleRoute: typeof AuthScheduleRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthTrayRoute: typeof AuthTrayRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthSpecsSpecIdRoute: typeof AuthSpecsSpecIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBacklogRoute: AuthBacklogRoute,
  AuthInsightsRoute: AuthInsightsRoute,
  AuthScheduleRoute: AuthScheduleRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthTrayRoute: AuthTrayRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthSpecsSpecIdRoute: AuthSpecsSpecIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
