/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrayRouteRouteImport } from './routes/tray/route'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as ScheduleRouteRouteImport } from './routes/schedule/route'
import { Route as InboxRouteRouteImport } from './routes/inbox/route'
import { Route as BacklogRouteRouteImport } from './routes/backlog/route'
import { Route as IndexRouteRouteImport } from './routes/index/route'
import { Route as WorkspacesNewRouteRouteImport } from './routes/workspaces/new/route'
import { Route as SettingsSectionIdRouteRouteImport } from './routes/settings/$sectionId/route'
import { Route as BacklogSpecsRouteRouteImport } from './routes/backlog/specs/route'
import { Route as BacklogActionsRouteRouteImport } from './routes/backlog/actions/route'
import { Route as AuthSignupRouteRouteImport } from './routes/auth/signup/route'
import { Route as AuthLoginRouteRouteImport } from './routes/auth/login/route'
import { Route as SettingsIndexRouteRouteImport } from './routes/settings/index/route'
import { Route as ScheduleBlockBlockIdRouteRouteImport } from './routes/schedule/block/$blockId/route'
import { Route as BacklogSpecsSpecIdRouteRouteImport } from './routes/backlog/specs/$specId/route'

const TrayRouteRoute = TrayRouteRouteImport.update({
  id: '/tray',
  path: '/tray',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRouteRoute = ScheduleRouteRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRouteRoute = InboxRouteRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const BacklogRouteRoute = BacklogRouteRouteImport.update({
  id: '/backlog',
  path: '/backlog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRouteRoute = IndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspacesNewRouteRoute = WorkspacesNewRouteRouteImport.update({
  id: '/workspaces/new',
  path: '/workspaces/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSectionIdRouteRoute = SettingsSectionIdRouteRouteImport.update({
  id: '/$sectionId',
  path: '/$sectionId',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const BacklogSpecsRouteRoute = BacklogSpecsRouteRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => BacklogRouteRoute,
} as any)
const BacklogActionsRouteRoute = BacklogActionsRouteRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => BacklogRouteRoute,
} as any)
const AuthSignupRouteRoute = AuthSignupRouteRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRouteRoute = AuthLoginRouteRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRouteRoute = SettingsIndexRouteRouteImport.update({
  id: '/',
  path: '',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ScheduleBlockBlockIdRouteRoute =
  ScheduleBlockBlockIdRouteRouteImport.update({
    id: '/block/$blockId',
    path: '/block/$blockId',
    getParentRoute: () => ScheduleRouteRoute,
  } as any)
const BacklogSpecsSpecIdRouteRoute = BacklogSpecsSpecIdRouteRouteImport.update({
  id: '/$specId',
  path: '/$specId',
  getParentRoute: () => BacklogSpecsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRouteRoute
  '/backlog': typeof BacklogRouteRouteWithChildren
  '/inbox': typeof InboxRouteRoute
  '/schedule': typeof ScheduleRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/tray': typeof TrayRouteRoute
  '/settings/': typeof SettingsIndexRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/signup': typeof AuthSignupRouteRoute
  '/backlog/actions': typeof BacklogActionsRouteRoute
  '/backlog/specs': typeof BacklogSpecsRouteRouteWithChildren
  '/settings/$sectionId': typeof SettingsSectionIdRouteRoute
  '/workspaces/new': typeof WorkspacesNewRouteRoute
  '/backlog/specs/$specId': typeof BacklogSpecsSpecIdRouteRoute
  '/schedule/block/$blockId': typeof ScheduleBlockBlockIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRouteRoute
  '/backlog': typeof BacklogRouteRouteWithChildren
  '/inbox': typeof InboxRouteRoute
  '/schedule': typeof ScheduleRouteRouteWithChildren
  '/settings': typeof SettingsIndexRouteRoute
  '/tray': typeof TrayRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/signup': typeof AuthSignupRouteRoute
  '/backlog/actions': typeof BacklogActionsRouteRoute
  '/backlog/specs': typeof BacklogSpecsRouteRouteWithChildren
  '/settings/$sectionId': typeof SettingsSectionIdRouteRoute
  '/workspaces/new': typeof WorkspacesNewRouteRoute
  '/backlog/specs/$specId': typeof BacklogSpecsSpecIdRouteRoute
  '/schedule/block/$blockId': typeof ScheduleBlockBlockIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRouteRoute
  '/backlog': typeof BacklogRouteRouteWithChildren
  '/inbox': typeof InboxRouteRoute
  '/schedule': typeof ScheduleRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/tray': typeof TrayRouteRoute
  '/settings/': typeof SettingsIndexRouteRoute
  '/auth/login': typeof AuthLoginRouteRoute
  '/auth/signup': typeof AuthSignupRouteRoute
  '/backlog/actions': typeof BacklogActionsRouteRoute
  '/backlog/specs': typeof BacklogSpecsRouteRouteWithChildren
  '/settings/$sectionId': typeof SettingsSectionIdRouteRoute
  '/workspaces/new': typeof WorkspacesNewRouteRoute
  '/backlog/specs/$specId': typeof BacklogSpecsSpecIdRouteRoute
  '/schedule/block/$blockId': typeof ScheduleBlockBlockIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backlog'
    | '/inbox'
    | '/schedule'
    | '/settings'
    | '/tray'
    | '/settings/'
    | '/auth/login'
    | '/auth/signup'
    | '/backlog/actions'
    | '/backlog/specs'
    | '/settings/$sectionId'
    | '/workspaces/new'
    | '/backlog/specs/$specId'
    | '/schedule/block/$blockId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/backlog'
    | '/inbox'
    | '/schedule'
    | '/settings'
    | '/tray'
    | '/auth/login'
    | '/auth/signup'
    | '/backlog/actions'
    | '/backlog/specs'
    | '/settings/$sectionId'
    | '/workspaces/new'
    | '/backlog/specs/$specId'
    | '/schedule/block/$blockId'
  id:
    | '__root__'
    | '/'
    | '/backlog'
    | '/inbox'
    | '/schedule'
    | '/settings'
    | '/tray'
    | '/settings/'
    | '/auth/login'
    | '/auth/signup'
    | '/backlog/actions'
    | '/backlog/specs'
    | '/settings/$sectionId'
    | '/workspaces/new'
    | '/backlog/specs/$specId'
    | '/schedule/block/$blockId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRouteRoute: typeof IndexRouteRoute
  BacklogRouteRoute: typeof BacklogRouteRouteWithChildren
  InboxRouteRoute: typeof InboxRouteRoute
  ScheduleRouteRoute: typeof ScheduleRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  TrayRouteRoute: typeof TrayRouteRoute
  AuthLoginRouteRoute: typeof AuthLoginRouteRoute
  AuthSignupRouteRoute: typeof AuthSignupRouteRoute
  WorkspacesNewRouteRoute: typeof WorkspacesNewRouteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tray': {
      id: '/tray'
      path: '/tray'
      fullPath: '/tray'
      preLoaderRoute: typeof TrayRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backlog': {
      id: '/backlog'
      path: '/backlog'
      fullPath: '/backlog'
      preLoaderRoute: typeof BacklogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspaces/new': {
      id: '/workspaces/new'
      path: '/workspaces/new'
      fullPath: '/workspaces/new'
      preLoaderRoute: typeof WorkspacesNewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/$sectionId': {
      id: '/settings/$sectionId'
      path: '/$sectionId'
      fullPath: '/settings/$sectionId'
      preLoaderRoute: typeof SettingsSectionIdRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/backlog/specs': {
      id: '/backlog/specs'
      path: '/specs'
      fullPath: '/backlog/specs'
      preLoaderRoute: typeof BacklogSpecsRouteRouteImport
      parentRoute: typeof BacklogRouteRoute
    }
    '/backlog/actions': {
      id: '/backlog/actions'
      path: '/actions'
      fullPath: '/backlog/actions'
      preLoaderRoute: typeof BacklogActionsRouteRouteImport
      parentRoute: typeof BacklogRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: ''
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/schedule/block/$blockId': {
      id: '/schedule/block/$blockId'
      path: '/block/$blockId'
      fullPath: '/schedule/block/$blockId'
      preLoaderRoute: typeof ScheduleBlockBlockIdRouteRouteImport
      parentRoute: typeof ScheduleRouteRoute
    }
    '/backlog/specs/$specId': {
      id: '/backlog/specs/$specId'
      path: '/$specId'
      fullPath: '/backlog/specs/$specId'
      preLoaderRoute: typeof BacklogSpecsSpecIdRouteRouteImport
      parentRoute: typeof BacklogSpecsRouteRoute
    }
  }
}

interface BacklogSpecsRouteRouteChildren {
  BacklogSpecsSpecIdRouteRoute: typeof BacklogSpecsSpecIdRouteRoute
}

const BacklogSpecsRouteRouteChildren: BacklogSpecsRouteRouteChildren = {
  BacklogSpecsSpecIdRouteRoute: BacklogSpecsSpecIdRouteRoute,
}

const BacklogSpecsRouteRouteWithChildren =
  BacklogSpecsRouteRoute._addFileChildren(BacklogSpecsRouteRouteChildren)

interface BacklogRouteRouteChildren {
  BacklogActionsRouteRoute: typeof BacklogActionsRouteRoute
  BacklogSpecsRouteRoute: typeof BacklogSpecsRouteRouteWithChildren
}

const BacklogRouteRouteChildren: BacklogRouteRouteChildren = {
  BacklogActionsRouteRoute: BacklogActionsRouteRoute,
  BacklogSpecsRouteRoute: BacklogSpecsRouteRouteWithChildren,
}

const BacklogRouteRouteWithChildren = BacklogRouteRoute._addFileChildren(
  BacklogRouteRouteChildren,
)

interface ScheduleRouteRouteChildren {
  ScheduleBlockBlockIdRouteRoute: typeof ScheduleBlockBlockIdRouteRoute
}

const ScheduleRouteRouteChildren: ScheduleRouteRouteChildren = {
  ScheduleBlockBlockIdRouteRoute: ScheduleBlockBlockIdRouteRoute,
}

const ScheduleRouteRouteWithChildren = ScheduleRouteRoute._addFileChildren(
  ScheduleRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsIndexRouteRoute: typeof SettingsIndexRouteRoute
  SettingsSectionIdRouteRoute: typeof SettingsSectionIdRouteRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsIndexRouteRoute: SettingsIndexRouteRoute,
  SettingsSectionIdRouteRoute: SettingsSectionIdRouteRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRouteRoute: IndexRouteRoute,
  BacklogRouteRoute: BacklogRouteRouteWithChildren,
  InboxRouteRoute: InboxRouteRoute,
  ScheduleRouteRoute: ScheduleRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  TrayRouteRoute: TrayRouteRoute,
  AuthLoginRouteRoute: AuthLoginRouteRoute,
  AuthSignupRouteRoute: AuthSignupRouteRoute,
  WorkspacesNewRouteRoute: WorkspacesNewRouteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
